config-version = "2.5"
# Change this to 25567 so bridge.js can talk to it
bind = "127.0.0.1:25567"
online-mode = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

[servers]
default = "mycuba.live:25594"
try = ["default"]

[motd]
motd = "Musawer Proxy"
show-max-players = 20
