bind = "0.0.0.0:25567"
online-mode = false
player-info-forwarding-mode = "legacy"
forwarding-secret-file = "forwarding.secret"

[servers]
default = "mycuba.live:25594"

# New forced-hosts syntax (array of tables)
[[forced-hosts]]
host = "musawer-server-1.onrender.com"
server = "default"

motd = "Musawer Eaglercraft Proxy"
show-max-players = 100
