bind = "0.0.0.0:25567"
motd = "Eaglercraft Proxy"
show-max-players = 100
online-mode = false

player-info-forwarding-mode = "legacy"
forwarding-secret-file = "forwarding.secret"

[servers]
backend = "mycuba.live:25594"
lobby = "mycuba.live:25594"

[forced-hosts]
"musawer-server-1.onrender.com" = ["backend"]
