bind = "0.0.0.0:25567"
online-mode = false
player-info-forwarding-mode = "legacy"
forwarding-secret-file = "forwarding.secret"

[servers]
default = "mycuba.live:25594"

[forced-hosts]
"musawer-server-1.onrender.com" = "default"

motd = "Musawer's Server :)"
show-max-players = 20
